#!/bin/sh
# Modifies the Makefile in the current directory (and optionally its subdirs),
# - to add debug info (-g3)
# - optionally (default) remove optimizations (-O[1-9]?)

mxdp="-maxdepth 1"
for i in $*; do
  case $i in
    -k) keep=1;;
    -r) mxdp=;;
    *) echo -e "Usage: adddebug [-k] [-r]\n  -k: keep optimizations (removed by default)\n  -r: recursive (process all subdirectories)"; exit 1;;
  esac
done

xpr='s/^((C|CXX|LD)FLAGS[ \t]*=.*)$/\1 -g3/'
if test -z $keep; then
  xpr="$xpr;"'s/[\t ]-O[1-9]?\b//g'
fi
find . $mxdp -name Makefile -exec perl -pi -e "$xpr" {} \;
