#!/bin/sh

oldname=$1
newname=$2

if [ $# != 2 ]; then
    echo "Usage: $0 old_classname new_classname"
    exit 1
fi

oldfile=`echo $oldname | tr A-Z a-z`
newfile=`echo $newname | tr A-Z a-z`

if [ ! -f $newfile.h ]; then
    if [ -f ${oldfile}.h ]; then
        git mv $oldfile.h $newfile.h
    fi
    git mv $oldfile.cpp $newfile.cpp
    if [ -f ${oldfile}_p.h ]; then
        git mv ${oldfile}_p.h ${newfile}_p.h
    fi
fi

# Update buildsystem
perl -pi -e "s/$oldfile\.cpp/$newfile.cpp/" CMakeLists.txt

# Rename class
if [ -f ${newfile}.h ]; then
    perl -pi -e "s/$oldname/$newname/g" ${newfile}.h
fi
perl -pi -e "s/$oldname/$newname/g" $newfile.cpp
if [ -f ${newfile}_p.h ]; then
    perl -pi -e "s/$oldname/$newname/g" ${newfile}_p.h
fi

oldinclguard=`echo $oldname | tr a-z A-Z`
newinclguard=`echo $newname | tr a-z A-Z`

# Update include guard
if [ -f ${newfile}.h ]; then
    perl -pi -e "s/$oldinclguard/$newinclguard/g" $newfile.h
fi
if [ -f ${newfile}_p.h ]; then
    perl -pi -e "s/$oldinclguard/$newinclguard/g" ${newfile}_p.h
fi

# Update include in cpp file
perl -pi -e 's/\b'$oldfile'\.h/'$newfile'\.h/;s/\b'$oldfile'_p\.h/'$newfile'_p\.h/' $newfile.cpp

