#!/bin/sh

oldname=$1
newname=$2

if [ $# != 2 ]; then
    echo "Usage: $0 old_classname new_classname"
    exit 1
fi

oldfile=`echo $oldname | tr A-Z a-z`
newfile=`echo $newname | tr A-Z a-z`

if [ ! -f $newfile.h ]; then
    SVN_INFO=$(svn info 2>/dev/null)
    if test -n "$SVN_INFO"; then
        svn mv $oldfile.h $newfile.h
        svn mv $oldfile.cpp $newfile.cpp
    else
        git mv $oldfile.h $newfile.h
        git mv $oldfile.cpp $newfile.cpp
    fi
fi

# Update buildsystem
perl -pi -e "s/\b$oldfile\.cpp/$newfile.cpp/" CMakeLists.txt

# Rename class
perl -pi -e "s/\b$oldname/$newname/g" $newfile.h $newfile.cpp

oldinclguard=`echo $oldname | tr a-z A-Z`
newinclguard=`echo $newname | tr a-z A-Z`

# Update include guard
perl -pi -e "s/\b$oldinclguard/$newinclguard/g" $newfile.h

# Update include in cpp file
perl -pi -e 's/\b'$oldfile'\.h/'$newfile'\.h/' $newfile.cpp


