#!/usr/bin/perl -w

unless (scalar(@ARGV) == 1)
{
  die "Usage: check_licenses directory";
}

my $gpl = 'General\sPublic\sLicense';
my $gp2 = 'This\sis\sfree\ssoftware;';
my $gp3 = 'This\s(library|program)\sis\sfree\ssoftware;';
my $x11 = 'TORT\sOR\sOTHERWISE';
my $bsd = 'INCLUDING\sNEGLIGENCE\sOR\sOTHERWISE';
my $gen = 'generated';

sub nameok()
{
  my $f = shift;

  if ($f =~ /\.C$/ or $f =~ /\.cpp$/ or $f =~ /\.c$/ or $f =~ /\.h$/)
  {
    if ($f =~ /\.cpp$/)
    {
      if
        (
              $f !~ /meta_unload\.cpp$/
         and  $f !~ /_stub\.cpp/
         and  $f !~ /_skel.cpp/
         and  $f !~ /_closure\.cpp/
         and  $f !~ /moc\.cpp/
        )
      {
        return 1;
      }
      else
      {
        return 0;
      }
    }
    else
    {
      return 1;
    }
  }
  else
  {
    return 0;
  }
}

sub recursive_check()
{
  my $dir = shift;

  opendir (DIR, $dir) or die "Can't open $dir";

  my @filenames = grep { /^[^\.]/ } readdir(DIR);

  for my $f (@filenames)
  {
    my $filename = "$dir/$f";

    if (-d $filename)
    {
      &recursive_check($filename);
    }
    elsif (-f $filename and &nameok($filename))
    {
      open (IN, "<$filename") or die "Can't open $filename";
      undef $/;
      my $contents = <IN>;

      my $license = "!";

      if ($contents =~ m/$gpl/) { $license = "G"; }
      elsif ($contents =~ m/$gp2/) { $license = "G"; }
      elsif ($contents =~ m/$gp3/) { $license = "G"; }
      elsif ($contents =~ m/$x11/) { $license = "X"; }
      elsif ($contents =~ m/$bsd/) { $license = "B"; }
      elsif ($contents =~ m/$gen/) { $license = "g"; }

      print "$license $filename\n";
    }
  }
}

&recursive_check($ARGV[0]);

