#!/bin/sh
# Usage : create_makefiles dir
# (to be run from toplevel directory)
# Will re-create all Makefiles in dir and its subdirs
# Needs create_makefile in the path.
#
# Stupid, but handy.
# David Faure <faure@kde.org>
#
find $1 -type d | grep -v '\.libs' | grep -v '\.deps' | grep -v CVS | while read a; do create_makefile $a ; done

