#!/bin/sh
# This script makes a preliminary svn:ignore in the current dir by
# adding some standard stuff according to Makefile.am.
# License: GPL

addignore() {
	test -f svnignore.tmp || touch svnignore.tmp
	grep -q "^$1\$" svnignore.tmp || \
	( echo "$1" >> svnignore.tmp && echo "added $1 to svn:ignore" )
}

recurse=0
if test $# -eq 1; then
	if test "$1" = "-r"; then
		recurse=1
	fi
fi

handledir() {
	(
	cd $1
	trap "rm svnignore.tmp" 1 2 15
	if test -f Makefile.am; then
		if test $recurse -eq 1; then
			echo "Entering $1"
		fi
		addignore CVS
		addignore .cvsignore
		addignore Makefile
		addignore Makefile.in
		addignore Makefile.rules.in
		addignore Makefile.calls.in

		bins=`perl -p -e 's/\\\s*\n/ /g' Makefile.am | grep _PROGRAMS | sed -e 's/.*=\s*//;s/#.*//;s/\$([^)]*)//'`
		if test -n "$bins"; then
			for prog in $bins; do
				addignore "$prog"
			done
		fi

		svn propset svn:ignore -F svnignore.tmp .
		rm svnignore.tmp
	else
		echo "Skipping $1"
	fi
	)
}


if test -f Makefile.am; then
	if test $recurse -eq 1; then
		find . -type d | egrep -v 'CVS|.svn' | sed -e 's,/$,,' | \
		while read dir; do
			handledir $dir
		done
	else
		handledir .
	fi
else
	echo "No Makefile.am found!"
fi

