#!/bin/sh

# Create Makefile.in and Makefile in a directory (containing a Makefile.am !)
# Must be run from the toplevel directory (i.e. the one containing configure)
# Saves time compared to re-running configure completely

if [ $# -ne 1 ]; then 
  echo "$0 : creates a Makefile from a Makefile.am"
  echo
  echo "Usage : $0 relativepath/Makefile"
  echo "So the argument is the file you want to create."
  echo
else
  if test ! -f Makefile; then 
    echo "$0: in the current directory there is no Makefile"
    echo "you will have to run it from the top build dir."
    echo "if you do not have a Makefile there - rerun configure"
    exit
  fi

  srcdir=`egrep '^srcdir *=' Makefile | sed -e "s#srcdir *= *##"`
  (  
    if cd $srcdir ; then 
     automake $* || exit
     if test -f admin/am_edit; then perl admin/am_edit $*.in ;\
     else 
       if test -f admin/automoc; then perl admin/automoc $*.in ; \
       else
         if test -f automoc; then perl automoc -v $*.in; fi
       fi
     fi
    fi
  )
  CONFIG_FILES=$* CONFIG_HEADERS= ./config.status
fi
