#!/bin/sh
# Usage : create_makefiles dir
# (to be run from toplevel directory)
# Will re-create all Makefiles in dir and its subdirs
# Needs create_makefile in the path.
#
# David Faure <faure@kde.org>

srcdir=`egrep '^srcdir *=' Makefile | sed -e "s#srcdir *= *##"`
 
( cd $srcdir ; find $1 -name Makefile.am ) | \
  sed -e 's/Makefile\.am/Makefile/' |
  while read a; do create_makefile $a ; done

