#!/usr/bin/perl

use File::Basename;

$cvsversion= dirname($0) . "/cvsversion";
$version=`$cvsversion $ARGV[0]`;

chop $version;
if ($version=~/^(.*)\.([^.]*)$/) { $v1 = $1; $v2 = $2 }    
$v2old = ${v2}-1;
print "cvs diff -b -u -r$v1.$v2old -r$v1.$v2 $ARGV[0]\n";
system("cvs diff -b -u -r$v1.$v2old -r$v1.$v2 $ARGV[0]");
