#! /usr/bin/perl

$filename = "";
@filenames = ();

sub writeoutstring($)
{
   print STDOUT "i18n(\"@_[0]\"); // $filename \n";
}

while (defined ($ARGV[0]))
{
   $_ = shift; 
   $filename = $_; # maybe check for options

if (! $filename) {
   print STDERR "no file to open\n";
   exit 1;
}

$string = "";
$intext = 0;
$linenr = 0;

open(FILE, $filename);

READING: while ( <FILE> ) {
   $linenr++;
   if ($linenr == 1 && ($_ !~ /^<!DOCTYPE/) && ($_ !~ /^<\?xml/)) {
   	last READING;
   }

   $string .= "\\n" . $_;   
   chomp($string);
 
   $textstring = '([tT][eE][xX][tT]|title|string)>';

   if ($intext == 0) {
     if ($string =~ /<$textstring/) {
       $string =~ s/^.*<$textstring//;
       $intext = 1;
	   $starting_linenr = $linenr;
     } else {
       $string = "";
     }
   }
   
   if (($intext == 1) && ($string =~ /<\/$textstring/)) {
     my $text = $string;
     $text =~ s/<\/$textstring.*$//;
	 $text =~ s/&lt;/</g;
     $text =~ s/&gt;/>/g;
     $text =~ s/&amp;/&/g; 
     $text =~ s/\"/\\\"/g;
     writeoutstring($text); 
     $string =~ s/^.*<\/$textstring//;
     $intext = 0;
	 if ($linenr != $starting_linenr && $filename =~ m/\.rc$/) {
		print STDERR "there is <text> floating $filename\n";
     }
   }

}

if ($intext == 1) {
 print STDERR "parsing error in $filename $linenr\n";
 exit 1;
}

}
