#!/bin/sh
# Run from command line, to open a qt help page in kfm/konqueror
# No argument => main page
# Classname (case insensitive) => page for this class

if [ $# = 1 ]; then
  fname=`echo $1 | tr '[A-Z]' '[a-z]'`
  if [ -f $QTDIR/doc/html/$fname.html ]; then
    kdeinit_wrapper kfmclient openProfile webbrowsing file:$QTDIR/doc/html/$fname.html
  else
    if [ -f /usr/doc/qt2/html/$fname.html ]; then
      kdeinit_wrapper kfmclient openProfile webbrowsing file:/usr/doc/qt2/html/$fname.html
    else
      echo "No such file $fname.html"
    fi
  fi
else
  kfmclient openURL file:$QTDIR/doc/html/index.html
fi
