#!/bin/sh

#
# This script recursively (beginning with the current directory)
# wipes out everything not registered in SVN.
#
# written by Thiago Macieira <thiago@kde.org>
#  inspired by cvs-clean, written by Oswald Buddenhagen <ossi@kde.org>
#   inspired by the "old" cvs-clean target from Makefile.common
#
# This file is free software in terms of the BSD licence. That means
# that you can do anything with it except removing this license or
# the above copyright notice. There is NO WARRANTY of any kind.
#

# Warning:
# This script processes the output from the SVN executable
# Do not run it along with colorsvn

SVN=`type -p svn`
RM=/bin/rm

if [ -z "$SVN" ]; then
    echo "Subversion executable (svn) not found" >&2
    echo "Aborting" >&2

    exit 1
fi

if [ \! -x "$SVN" ]; then
    echo "Cannot run svn: \`$SVN' is not executable" >&2
    echo "Aborting" >&2

    exit 1
fi

# Parse -n argument: dry-run
if [ "$1" = "-n" ]; then
    RM=/bin/true
    shift
fi

# Unset TERM just so that no colours are output
# in case $SVN points to colorsvn
unset TERM

$SVN status --no-ignore | grep '^[I?]' | cut -b8- | \
    while read file; do
    if [ -f $file -o -L $file ]; then
	echo "F $file"
	$RM $file
    elif [ -d $file ]; then
	echo "D $file"
	$RM -r $file
    else
	echo "? $file"
	$RM -r $file
    fi
done
