#!/bin/sh

if [ $# -eq 0 ]; then
    cat <<EOF
Usage:
    svnlastchange <filename> [<filename> ...]

EOF
    exit 1
fi
echo >&2 "Warning: svnlastchange is superfluous"
echo >&2 "Use svn log -r COMMITTED and svn diff -r PREV:COMMITTED"

svn log -r COMMITTED "$*"
svn diff -r PREV:COMMITTED "$*" || \
    echo >&2 "Error retrieving diff: the file was probably added in the last revision"